function ActvityGenerateReport() {
    // Obtiene los valores seleccionados por el usuario
    var startDate = $('#StartDate').val();
    var endDate = $('#EndDate').val();
    var user = $('#user').val();

    // Datos de ejemplo de garantías (puedes ajustarlos según tus necesidades)
    var activity = [
        { user: 'EJohnson01', name: 'Emma Johnson', timein: '2023-11-30 8:30am', timeOut: '2023-11-30 4:30pm',  duration: ' 8 hrs',role:"Admin" },
        { user: 'WRodriguez02 ',name: 'Wendy Rodriguez ', timein: '2023-11-30 8:30am', timeOut: '2023-11-30 4:30pm', duration: ' 8 hrs' ,role:"Sales"},
        { user: 'WMitchell03', name: 'Wlliam Mitchell', timein:'2023-11-30 8:30am', timeOut: '2023-11-30 4:30pm',  duration:' 8 hrs',role:"Sales" },
        { user: 'SThompson04 ', name: 'Sam Thompson ', timein: '2023-11-30 8:30am', timeOut: '2023-11-30 4:30pm', duration: 'hrs',role:"Ordering and Purchasing" },
        { user: 'EParker05 ', name: 'Emily Parker', timein:'2023-11-30 8:30am', timeOut: '2023-11-30 4:30pm',  duration: 'hrs',role:"Admin" },

        // Agrega más garantías según sea necesario
    ];

    

      // Crear la estructura HTML para el informe
      var htmlContent = `
    <div class="report-container">
          
              <p>Emmas Small Engines</p>
              <h3>Activity User Report</h3>
              <hr />
              <p>Date generated: ${getCurrentDate()}</p>
              <p>Generated by: Emma</p>
              <p>Report date range: ${startDate} - ${endDate}</p>
              <p>Role: Admin</p>
              <p>User Reported: ${user}</p>
              <table border="1">
                  <thead class="table-light">
                      <tr>
                          <th>User Name</th>
                          <th>Full Name</th>
                          <th>Time Log in</th>
                          <th>Time Log Out</th>
                          <th>Duration</th>
                          <th>Role</th>
                      </tr>
                  </thead>
                  <tbody>`;

        // Agregar filas de datos
        activity.forEach(activity => {
            htmlContent += `
                  <tr>
                      <td>${activity.user}</td>
                      <td>${activity.name}</td>
                      <td>${activity.timein}</td>
                      <td>${activity.timeOut}</td>
                      <td>${activity.duration}</td>
                      <td>${activity.role}</td>
                  </tr>`;
  });

  // Cerrar la estructura HTML de la tabla
  htmlContent += `
                    </tbody>
                </table>
            
        </div>`;

    // Obtener el contenedor del informe
    var reportContainer = document.getElementById('ActvityReportContainer');

    // Asignar el contenido HTML al contenedor
    reportContainer.innerHTML = htmlContent;

    // Mostrar el contenedor cambiando el estilo display a 'flex'
    reportContainer.style.display = 'block';
}

