
function ActivityExportReport() {
    // Obtiene los valores seleccionados por el usuario
var startDate = $('#StartDate').val();
var endDate = $('#EndDate').val();
var status = $('#user').val();


var doc = new jsPDF();

  // Encabezado
  doc.setFontSize(14);
  doc.text("Emmas Small Engines", 10, 10);
  doc.text("User Activity Report", 80, 20);
  doc.line(10, 22, 200, 22);
  doc.setFontSize(10);

  // Información del reporte
  doc.text("Date generated: " + getCurrentDate(), 10, 30);
  doc.text("Generated by: Emma", 10, 40);
  doc.text("Report date range: " + startDate + " - " + endDate, 10, 50);
  // Agregar el departamento de la persona que lo generó
  doc.text("Role: Admin", 10, 60);
  

  doc.autoTable({
    html: '#ActivityReportTablepdf',
    startY: 70,
    theme: 'grid',
    headStyles :{lineWidth: .5,fillColor: [26, 137, 241],textColor: [255,255,255],
    },
    columnStyles: {
        0: {
            halign: 'right',
            tableWidth: 100,
            },
        1: {
            tableWidth: 100,
           },
        2: {
            halign: 'right',
            tableWidth: 100,
           },
        3: {
            halign: 'right',
            tableWidth: 100,
           }
    },

})



doc.save("Activity_Report.pdf");
}
function getCurrentDate() {
var today = new Date();
var dd = String(today.getDate()).padStart(2, '0');
var mm = String(today.getMonth() + 1).padStart(2, '0'); // Enero es 0
var yyyy = today.getFullYear();
return dd + '/' + mm + '/' + yyyy;
}


document.addEventListener("DOMContentLoaded", function() {
    // Get the elements
    var repairReportLink = document.getElementById("profile-tab");
    var warrantyReportContainer = document.getElementById("warrantyReportContainer");
    var RepairReportContainer = document.getElementById("RepairReportContainer");
  
    // Add a click event listener to the "Repair Report" link
    repairReportLink.addEventListener("click", function(event) {
      // Prevent the default behavior (navigation)
      event.preventDefault();
  
      // Hide the warranty report container
      warrantyReportContainer.style.display = "none";
      RepairReportContainer.style.display = "none";
    });
});
