function warrantyGenerateReport() {
    // Obtiene los valores seleccionados por el usuario
    var startDate = $('#StartDate').val();
    var endDate = $('#EndDate').val();
    var company = $('#company').val();

    // Datos de ejemplo de garantías (puedes ajustarlos según tus necesidades)
    var garantias = [
        { descripcion: 'Warranty 100987747', customerName: 'Jamie Dorito', duration: 6 +' hrs ', date: '2023-11-01',  cost: 50 },
        { descripcion: 'Warranty 100987748', customerName: 'Jane Smith ', duration: 45 +' hrs', date: '2023-11-07', cost: 600 },
        { descripcion: 'Warranty 100987749', customerName: 'Juan Smith ', duration: 6+' hrs', date: '2023-11-23',  cost: 300 },
        { descripcion: 'Warranty 100987750', customerName: 'Jeremy Domino ', duration: 18 + ' hrs', date: '2023-11-06', cost: 1000 },
        { descripcion: 'Warranty 100987751', customerName: 'Jerry Doom', duration: 6 +' hrs', date: '2023-11-15',  cost: 200 },

        // Agrega más garantías según sea necesario
    ];

    // Calcular el número total de garantías
    var totalGarantias = garantias.length;

    // Calcular el promedio de la duración
    var totalDuration = garantias.reduce((sum, garantia) => sum + garantia.duration, 0);
    var avgDuration = totalDuration / totalGarantias;

    // Calcular el número total de clientes servidos
    var customersServed = new Set(garantias.map(garantia => garantia.cliente)).size;

    // Calcular el costo total
    var totalCost = garantias.reduce((sum, garantia) => sum + garantia.cost, 0);

      // Crear la estructura HTML para el informe
      var htmlContent = `
    <div class="report-container">
          
              <p>Emmas Small Engines</p>
              <h3>Warranty Report</h3>
              <hr />
              <p>Date generated: ${getCurrentDate()}</p>
              <p>Generated by: Emma</p>
              <p>Report date range: ${startDate} - ${endDate}</p>
              <p>Company: ${company}</p>
              <p>Role: Admin</p>
              <table border="1">
                  <thead class="table-light">
                      <tr>
                          <th>Description</th>
                          <th>Customer Name</th>
                          <th>Duration</th>
                          <th>Date</th>
                          <th>Cost</th>
                      </tr>
                  </thead>
                  <tbody>`;

        // Agregar filas de datos
        garantias.forEach(garantia => {
            htmlContent += `
                  <tr>
                      <td>${garantia.descripcion}</td>
                      <td>${garantia.customerName}</td>
                      <td>${garantia.duration}</td>
                      <td>${garantia.date}</td>
                      <td>${garantia.cost}</td>
                  </tr>`;
  });

  // Cerrar la estructura HTML de la tabla
  htmlContent += `
                    </tbody>
                </table>
            <div class="totals">          
                <p>Total Warranties: ${totalGarantias}</p>
                <p>Average Duration: ${avgDuration.toFixed(2)} days</p>
                <p>Customers Served: ${customersServed}</p>
                <p>Total Cost: $${totalCost}</p>
           <div>
            
        </div>`;

    // Obtener el contenedor del informe
    var reportContainer = document.getElementById('warrantyReportContainer');

    // Asignar el contenido HTML al contenedor
    reportContainer.innerHTML = htmlContent;

    // Mostrar el contenedor cambiando el estilo display a 'flex'
    reportContainer.style.display = 'block';
}

